services:
  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    ports:
      - "6000:5432"
    volumes:
      - ./scripts/new-db:/docker-entrypoint-initdb.d/
      - ./db_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD",
          "/usr/bin/pg_isready",
          "--dbname=quikbroker",
          "--username=quikbroker_owner",
        ]
      interval: 5s
      timeout: 10s
      retries: 120

  app:
    build:
      context: .
      dockerfile: ./packages/app/Dockerfile
    restart: always
    ports:
      # - "3003:3000"
      - "3003:8080"
    env_file:
      - .env
    depends_on:
      - db

  migrate:
    build:
      context: .
      dockerfile: ./packages/schema/Dockerfile
    volumes:
      - type: bind
        source: ./scripts
        target: /scripts
      # - type: bind
      #   source: ./packages/schema/dumps
      #   target: /app/dumps
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    entrypoint: [""]
    # Inspired by: https://docs.docker.com/compose/startup-order/
    # command: [ '/scripts/wait-for-port.sh', 'db:5432', '--timeout=0', '--', 'yarn', 'migrate' ]
    # command: [ '/scripts/wait-for-port.sh', 'db:5432', '--timeout=0', '--', 'docker-entrypoint.sh' ]
    command: ["docker-entrypoint.sh"]
    # networks:
    #   - default
