services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: db_name
    ports:
      - "6000:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data

  db-shadow:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: db_name
    ports:
      - "6001:5432"
    volumes:
      - ./db_data_shadow:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: ./packages/app/Dockerfile
    restart: always
    ports:
      # - "3003:3000"
      - "3003:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
