services:
  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    ports:
      - "6000:5432"
    volumes:
      - ./scripts/new-db:/docker-entrypoint-initdb.d/
      - ./db_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD",
          "/usr/bin/pg_isready",
          "--dbname=quikbroker",
          "--username=quikbroker_owner",
        ]
      interval: 5s
      timeout: 10s
      retries: 120

  app:
    build:
      context: .
      dockerfile: ./packages/app/Dockerfile
    restart: always
    ports:
      # - "3003:3000"
      - "3003:8080"
    env_file:
      - .env
    depends_on:
      - db

  migrate:
    build:
      context: ./packages/migrations
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./scripts
        target: /scripts
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - SQITCH_TARGET=db:pg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    command: ['deploy']
