name: Deploy to Railway

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT || '5432' }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:
  build-images:
    name: Build Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      migrations_image: ${{ steps.migrations-tag.outputs.image }}
      app_image: ${{ steps.app-tag.outputs.image }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and tag migrations image
      - name: Extract metadata for migrations image
        id: migrations-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/migrations
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha,format=short

      - name: Build and push migrations image
        id: build-migrations
        uses: docker/build-push-action@v5
        with:
          context: ./packages/migrations
          file: ./packages/migrations/Dockerfile
          push: true
          tags: ${{ steps.migrations-meta.outputs.tags }}
          labels: ${{ steps.migrations-meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/migrations:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/migrations:buildcache,mode=max

      - name: Set migrations image tag
        id: migrations-tag
        run: |
          FIRST_TAG=$(echo "${{ steps.migrations-meta.outputs.tags }}" | cut -d',' -f1)
          echo "image=$FIRST_TAG" >> $GITHUB_OUTPUT
          echo "Using migrations image tag: $FIRST_TAG"

      # Build and tag app image
      - name: Extract metadata for app image
        id: app-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/app
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha,format=short

      - name: Build and push app image
        id: build-app
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packages/app/Dockerfile
          push: true
          tags: ${{ steps.app-meta.outputs.tags }}
          labels: ${{ steps.app-meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/app:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/app:buildcache,mode=max

      - name: Set app image tag
        id: app-tag
        run: |
          FIRST_TAG=$(echo "${{ steps.app-meta.outputs.tags }}" | cut -d',' -f1)
          echo "image=$FIRST_TAG" >> $GITHUB_OUTPUT
          echo "Using app image tag: $FIRST_TAG"

  run-migrations:
    name: Run Database Migrations
    needs: build-images
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'production' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run migrations
        run: |
          echo "Running migrations using image: ${{ needs.build-images.outputs.migrations_image }}"
          
          # Pull the migrations image
          docker pull ${{ needs.build-images.outputs.migrations_image }}
          
          # Run the migrations container with environment variables
          docker run --rm \
            -e DB_HOST=${{ env.DB_HOST }} \
            -e DB_PORT=${{ env.DB_PORT }} \
            -e DB_NAME=${{ env.DB_NAME }} \
            -e DB_USER=${{ env.DB_USER }} \
            -e DB_PASSWORD=${{ env.DB_PASSWORD }} \
            ${{ needs.build-images.outputs.migrations_image }} deploy

  deploy-app:
    name: Deploy Application to Railway
    needs: [build-images, run-migrations]
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'production' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install Railway CLI
        run: npm install -g @railway/cli
        
      - name: Set up Railway Token
        run: railway login --token ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy to Railway
        run: |
          echo "Deploying app image to Railway: ${{ needs.build-images.outputs.app_image }}"
          
          # Link to the Railway project
          railway link ${{ secrets.RAILWAY_PROJECT_ID }}
          
          # Deploy the container image to Railway
          railway service ${{ secrets.RAILWAY_SERVICE_ID }} \
            variables set \
            RAILWAY_DOCKERFILE_PATH=./packages/app/Dockerfile \
            RAILWAY_DOCKERFILE_IMAGE=${{ needs.build-images.outputs.app_image }}
          
          # Trigger deployment
          railway up --service ${{ secrets.RAILWAY_SERVICE_ID }} --detach