name: Docker Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  FLY_REGISTRY: registry.fly.io
  IMAGE_NAME: ${{ github.repository }}
  FLY_APP: quikbroker

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        image: [app, schema]
        include:
          - image: app
            dockerfile: ./packages/app/Dockerfile
          - image: schema
            dockerfile: ./packages/schema/Dockerfile

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          app: ${{ env.FLY_APP }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Fly.io Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.FLY_REGISTRY }}
          username: ${{ secrets.FLY_API_TOKEN }}
          password: x

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.image }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=long
          labels: |
            org.opencontainers.image.title=${{ matrix.image }}
            org.opencontainers.image.description=${{ matrix.image }} image for QuikBroker
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.visibility=private

      - name: Build and push Docker image to GitHub Registry
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.image }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.image }}:buildcache,mode=max

      - name: Debug metadata output
        run: |
          echo "All tags: ${{ steps.meta.outputs.tags }}"
          echo "All labels: ${{ steps.meta.outputs.labels }}"

      - name: Set image tag
        id: set-tag
        run: |
          # Try to get the latest tag, fall back to the first tag if not found
          if [[ "${{ steps.meta.outputs.tags }}" == *"latest"* ]]; then
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          else
            # Get the first tag from the comma-separated list
            FIRST_TAG=$(echo "${{ steps.meta.outputs.tags }}" | cut -d',' -f1)
            echo "IMAGE_TAG=$FIRST_TAG" >> $GITHUB_ENV
          fi
          echo "Using image tag: $IMAGE_TAG"

      - name: Tag and push to Fly.io Registry
        run: |
          echo "Pulling image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.image }}:$IMAGE_TAG"
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.image }}:$IMAGE_TAG
          
          echo "Tagging for Fly.io: ${{ env.FLY_REGISTRY }}/${{ env.FLY_APP }}:$IMAGE_TAG"
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.image }}:$IMAGE_TAG ${{ env.FLY_REGISTRY }}/${{ env.FLY_APP }}:$IMAGE_TAG
          
          echo "Pushing to Fly.io Registry: ${{ env.FLY_REGISTRY }}/${{ env.FLY_APP }}:$IMAGE_TAG"
          docker push ${{ env.FLY_REGISTRY }}/${{ env.FLY_APP }}:$IMAGE_TAG

      - name: Run SchemaMigrations
        # uses: superfly/flyctl-actions/setup-flyctl@master
        # with:
        #   app: ${{ env.FLY_APP }}
        # env:
        #   FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          flyctl proxy 5432 -a ${{ env.FLY_APP }} > /dev/null 2>&1 &
          sleep 5  # Wait for proxy to initialize
          
          # Run the Schema Migration
          docker run --rm -it ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/schema:$IMAGE_TAG


      - name: Deploy to Fly.io
        if: github.ref == 'refs/heads/main'
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          app: ${{ env.FLY_APP }}
          image: ${{ env.FLY_REGISTRY }}/${{ env.FLY_APP }}:$IMAGE_TAG
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
