name: Migrations Build and Deploy

on:
  push:
    branches: ["main"]
    paths:
      - "packages/migrations/**"
      - ".github/workflows/migrations-build.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "packages/migrations/**"
      - ".github/workflows/migrations-build.yml"
  workflow_dispatch:
    # Manual trigger

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for migrations image
        id: migrations-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/migrations
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=long
          labels: |
            org.opencontainers.image.title=migrations
            org.opencontainers.image.description=Database migrations for QuikBroker
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.visibility=private

      - name: Build and push migrations image
        id: build-migrations
        uses: docker/build-push-action@v5
        with:
          context: ./packages/migrations
          file: ./packages/migrations/Dockerfile
          push: true
          tags: ${{ steps.migrations-meta.outputs.tags }}
          labels: ${{ steps.migrations-meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/migrations:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/migrations:buildcache,mode=max

      - name: Set migrations image tag
        id: set-migrations-tag
        run: |
          if [[ "${{ steps.migrations-meta.outputs.tags }}" == *"latest"* ]]; then
            echo "MIGRATIONS_IMAGE_TAG=latest" >> $GITHUB_ENV
          else
            FIRST_TAG=$(echo "${{ steps.migrations-meta.outputs.tags }}" | cut -d',' -f1)
            echo "MIGRATIONS_IMAGE_TAG=$FIRST_TAG" >> $GITHUB_ENV
          fi
          echo "Using migrations image tag: $MIGRATIONS_IMAGE_TAG"

      - name: Display image info
        run: |
          echo "Migrations image has been built and pushed with tags:"
          echo "${{ steps.migrations-meta.outputs.tags }}"